import { TemplateConfig } from "./types";

export const TEMPLATES: TemplateConfig[] = [
  {
    id: "clarity",
    name: "Clarity",
    layout: "single-column",
    accentColor: "#17B890",
    headingFont: "'Space Grotesk', sans-serif",
    bodyFont: "'Inter', sans-serif",
    density: "spacious",
  },
  {
    id: "executive",
    name: "Executive",
    layout: "sidebar-left",
    accentColor: "#0B1220",
    headingFont: "'Georgia', serif",
    bodyFont: "'Inter', sans-serif",
    density: "spacious",
  },
  {
    id: "modern-band",
    name: "Modern Band",
    layout: "header-band",
    accentColor: "#0B1220",
    headingFont: "'Space Grotesk', sans-serif",
    bodyFont: "'Inter', sans-serif",
    density: "spacious",
  },
  {
    id: "compact-pro",
    name: "Compact Pro",
    layout: "single-column",
    accentColor: "#475569",
    headingFont: "'Inter', sans-serif",
    bodyFont: "'Inter', sans-serif",
    density: "compact",
  },
  {
    id: "minimal-mono",
    name: "Minimal Mono",
    layout: "single-column",
    accentColor: "#17B890",
    headingFont: "'JetBrains Mono', monospace",
    bodyFont: "'Inter', sans-serif",
    density: "spacious",
  },
  {
    id: "sidebar-right",
    name: "Sidebar Right",
    layout: "sidebar-right",
    accentColor: "#F5A623",
    headingFont: "'Space Grotesk', sans-serif",
    bodyFont: "'Inter', sans-serif",
    density: "spacious",
  },
  {
    id: "timeline",
    name: "Timeline",
    layout: "single-column",
    accentColor: "#119374",
    headingFont: "'Inter', sans-serif",
    bodyFont: "'Inter', sans-serif",
    density: "spacious",
  },
  {
    id: "classic-serif",
    name: "Classic Serif",
    layout: "single-column",
    accentColor: "#1B2740",
    headingFont: "'Georgia', serif",
    bodyFont: "'Georgia', serif",
    density: "spacious",
  },
  {
    id: "bold-header",
    name: "Bold Header",
    layout: "single-column",
    accentColor: "#17B890",
    headingFont: "'Space Grotesk', sans-serif",
    bodyFont: "'Inter', sans-serif",
    density: "compact",
  },
  {
    id: "two-tone",
    name: "Two-Tone",
    layout: "sidebar-left",
    accentColor: "#34D3A6",
    headingFont: "'Space Grotesk', sans-serif",
    bodyFont: "'Inter', sans-serif",
    density: "spacious",
  },
];
