import { LegalLayout, LegalSection } from "@/shared/layout/LegalLayout";

export function TermsPage() {
  return (
    <LegalLayout title="Terms of Service">
      <LegalSection heading="1. Acceptance of terms">
        <p>
          By creating an account or using CareerPilot AI, you agree to these Terms of Service and
          our Privacy Policy. If you don't agree, please don't use the service.
        </p>
      </LegalSection>

      <LegalSection heading="2. What CareerPilot AI does">
        <p>CareerPilot AI provides AI-assisted career tools, including:</p>
        <ul className="list-disc space-y-1.5 pl-5">
          <li>Resume analysis and ATS scoring</li>
          <li>Job description analysis and resume-to-job matching</li>
          <li>Mock interview question generation and scored practice</li>
          <li>Resume building across multiple templates, with PDF and Word export</li>
        </ul>
      </LegalSection>

      <LegalSection heading="3. Your account">
        <p>
          You're responsible for keeping your login credentials secure and for all activity under
          your account. You must provide accurate information and are responsible for the
          accuracy of any resume, job description, or other content you submit.
        </p>
      </LegalSection>

      <LegalSection heading="4. AI-generated content — please read this section">
        <p>
          Scores, feedback, generated summaries, interview questions, and resume content produced
          by CareerPilot AI are generated by AI and are provided as suggestions, not as
          professional career counseling, employment, or legal advice. AI-generated content can
          be inaccurate or incomplete.
        </p>
        <p>
          You're responsible for reviewing and verifying anything before using it in a real job
          application, interview, or other real-world decision. We are not responsible for
          outcomes resulting from your use of AI-generated content, including hiring decisions
          made by third parties.
        </p>
      </LegalSection>

      <LegalSection heading="5. Acceptable use">
        <p>You agree not to:</p>
        <ul className="list-disc space-y-1.5 pl-5">
          <li>Upload another person's resume or personal information without their consent</li>
          <li>Attempt to circumvent free-plan usage limits</li>
          <li>Use the service for any unlawful purpose</li>
          <li>Attempt to interfere with or disrupt the service's infrastructure</li>
        </ul>
      </LegalSection>

      <LegalSection heading="6. Plans and usage limits">
        <p>
          CareerPilot AI is currently offered on a free plan with monthly limits on certain
          features, shown in the app. We may introduce a paid plan with additional usage in the
          future; if we do, these terms will be updated to reflect billing terms before any
          payment is required from you.
        </p>
      </LegalSection>

      <LegalSection heading="7. Your content">
        <p>
          You retain ownership of the resumes, job descriptions, and other content you submit. By
          submitting content, you grant us a limited license to process it solely to provide the
          service to you — including sending it to our AI provider for analysis, as described in
          our Privacy Policy.
        </p>
      </LegalSection>

      <LegalSection heading="8. Termination">
        <p>
          You may stop using the service at any time. We may suspend or terminate accounts that
          violate these terms.
        </p>
      </LegalSection>

      <LegalSection heading="9. Disclaimer and limitation of liability">
        <p>
          CareerPilot AI is provided "as is," without warranties of any kind. To the fullest
          extent permitted by law, we are not liable for indirect, incidental, or consequential
          damages arising from your use of the service.
        </p>
      </LegalSection>

      <LegalSection heading="10. Governing law">
        <p>These terms are governed by the laws of India.</p>
      </LegalSection>

      <LegalSection heading="11. Changes to these terms">
        <p>
          We may update these terms as the product changes. We'll update the "Last updated" date
          above when we do.
        </p>
      </LegalSection>

      <LegalSection heading="12. Contact us">
        <p>
          Questions about these terms can be sent to{" "}
          <span className="font-medium">[support email to be added]</span>.
        </p>
      </LegalSection>
    </LegalLayout>
  );
}
